version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
stages:
  - stage:
    name: compile
    displayName: 编译检查
    steps:
      - step: shell@agent
        name: build_maven
        displayName: Maven 编译
        image: maven:3.9-eclipse-temurin-17
        commands:
          - mvn -B clean compile

triggers:
  push:
    branches:
      exclude:
        - master
      include:
        - .*