version: '1.0'
name: pr-pipeline
displayName: PRPipeline
stages:
  - stage:
    name: unit-test
    displayName: 代码级测试（PR 门禁）
    steps:
      - step: build@maven
        name: build_and_test
        displayName: 编译并运行单元测试
        inputs:
          jdkVersion: 17
          mavenVersion: 3.6.3
        commands:
          - mvn -B clean test jacoco:report
        artifacts:
          - name: TEST_REPORT
            path:
              - ./target/surefire-reports
              - ./target/site/jacoco
      - step: publish@general_artifacts
        name: publish_test_reports
        displayName: 上传测试报告
        dependArtifact: TEST_REPORT
        artifactName: test-reports
        dependsOn: build_and_test

triggers:
  pr:
    branches:
      include:
        - master
